# This is a basic workflow to help you get started with Actions

name: Your github action

on:
  push:
    branches:
      # NOTE: You may want to limit the trigger branch to be "main" or "master" etc.
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
